### ISSUE TITLE
image path

### ISSUE THREAD

**Issue by anthonyschurz** [netguru/picguard#5]
Hi Guys,
Great gem! One of the things we're wondering about is the image path. How did you get the gem to work for users adding their own images (ie. images not already in the project, with a defined file path)? I assume this works after playing around with http://picguard.netguru.co/. Cheers!

``` ruby
def create
    @user = current_user
    @art_tags = Picguard.analyze(image_path: 'public/ducks.jpg')
    @art = Art.new({image: art_params[:image], user_id: @user.id, vision: @art_tags})
    if @art.save
      redirect_to "/"
    end
end
```

Basically we want public/ducks to be swapped out with a user uploaded image for analysis :)

**Comment by szymonbaranowski** [comment]
Hi @anthonyschurz, sorry for late response.
Not sure what is your intention here - If you want to process a file that is already uploaded you can achieve this with `Picguard.analyze` method, as in your example ( you can find more info [here](https://github.com/netguru/picguard#custom-usage) ). This is going to give you an answer if the file is valid - based on set thresholds.

For our [demo](http://picguard.netguru.co/) we used carrierwave and followed the pattern that can be found [here](https://github.com/netguru/picguard#carrierwave)
